In [2]:
import numpy as np

grades = np.array([85,90,88,92,95,80,75,98,89,83])

In [33]:
#mean
mean_grade = np.mean(grades)

In [34]:
#median
median_grade = np.median(grades)

In [35]:
#standard_deviation
standard_deviation = np.std(grades)

In [51]:
#min and max grades
min_grade = np.amin(grades)

max_grade = np.amax(grades)

In [52]:
max_grade

98

In [53]:
#sort grades in accending order
sorted_grade = np.sort(grades)

#find the index of the highest grade in the array.
index_of_highest_grade = np.argmax(grades)

In [39]:
index_of_highest_grade

7

In [40]:
sorted_grades_accending

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [41]:
#Use numpy function to count the number of students who scored above 90.

# Count the number of students who scored above 90
above_90_count = len(np.where(grades > 90)[0])

print(f"Number of students who scored above 90: {above_90_count}")

Number of students who scored above 90: 3


In [42]:
#numhy
#Use numpy function to calculate the percentage of students who scored above 90.
Total_students = len(grades)

percentage_above_90 = (above_90_count / Total_students ) * 100

In [43]:
percentage_above_90

30.0

In [44]:
#Use numpy function to calculate the percentage of students who scored below 75.
#sum() len(where), count_nonzero
below_75_count = np.count_nonzero(grades < 75)

percentage_below_75 = (below_75_count / Total_students) * 100

In [45]:
below_75_count

0

In [46]:
#extract all the grades above 90 and put them in a new array called "high_performers".
condition = grades > 90
high_performers = np.extract(condition,grades)

In [47]:
high_performers

array([92, 95, 98])

In [3]:
high_performer = grades[grades > 90]
high_performer

array([92, 95, 98])

In [48]:
#Create a new array called "passing_grades" that contains all the grades above 75.

passing_grades = grades[grades > 75]

In [49]:
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [54]:
# Print the results
print("Mean Grade:", mean_grade)
print("Median Grade:", median_grade)
print("Standard Deviation:", standard_deviation)
print("Maximum Grade:", max_grade)
print("Minimum Grade:", min_grade)
print("Sorted Grades:", sorted_grade)
print("Index of Highest Grade:", index_of_highest_grade)
print("Number of Students Above 90:", above_90_count)
print("Percentage of Students Above 90:", percentage_above_90, "%")
print("Percentage of Students Below 75:", percentage_below_75, "%")
print("High Performers:", high_performers)
print("Passing Grades:", passing_grades)

Mean Grade: 87.5
Median Grade: 88.5
Standard Deviation: 6.591661399070799
Maximum Grade: 98
Minimum Grade: 75
Sorted Grades: [75 80 83 85 88 89 90 92 95 98]
Index of Highest Grade: 7
Number of Students Above 90: 3
Percentage of Students Above 90: 30.0 %
Percentage of Students Below 75: 0.0 %
High Performers: [92 95 98]
Passing Grades: [85 90 88 92 95 80 98 89 83]
